# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b41d828e3a82de1be2ae57b09dfa1ac435aea33157ddac7ec6b72bf3f400bbe5356258dac85eaaa4e1b9aeee9247ef2e72f96c9594a25d3ba1586197284a81

test:
  secret_key_base: e05654f5bd26cba9915b83c6dcfe815b0121cdfd480ff5ed18cc51cac76e7089bdb371eed894bb6e4a9d0c79240bd2210c32ddba8471556e3f22e2f0f9961271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
